# Generated by Django 4.0.3 on 2022-12-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='age',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_login',
            name='gender',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
