# Generated by Django 4.0.3 on 2023-01-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0002_user_login_age_user_login_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_login',
            name='payment_status',
            field=models.BooleanField(),
        ),
    ]
