# Generated by Django 4.0.3 on 2023-01-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0003_alter_user_login_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='token',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
