# Generated by Django 4.0.3 on 2023-02-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0005_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='set_of_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
