# Generated by Django 4.0.3 on 2023-02-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0006_set_of_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_assigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('set_of_test_id', models.TextField()),
                ('completion_status', models.BooleanField(default=False)),
                ('listening_score', models.TextField()),
                ('reading_score', models.TextField()),
                ('writing_score', models.TextField()),
                ('speaking_score', models.TextField()),
                ('writing_remarks', models.TextField()),
                ('speaking_remarks', models.TextField()),
                ('admin_check_status', models.BooleanField(default=False)),
            ],
        ),
    ]
