# Generated by Django 4.0.3 on 2023-03-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0009_user_login_batch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch_creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.TextField(default='2023-03-05 14:27:49.499303+05:30')),
                ('student_count', models.TextField(default='0')),
            ],
        ),
    ]
