# Generated by Django 4.0.3 on 2023-03-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0011_alter_batch_creation_date_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_login',
            name='date_time',
            field=models.TextField(default='2023-03-05 15:42:46.922787+05:30'),
        ),
        migrations.AlterField(
            model_name='batch_creation',
            name='date_time',
            field=models.TextField(default='2023-03-05 15:42:46.922787+05:30'),
        ),
    ]
