# Generated by Django 4.0.3 on 2023-03-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0012_user_login_date_time_alter_batch_creation_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_assigned',
            name='listening_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test_assigned',
            name='reading_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test_assigned',
            name='speaking_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test_assigned',
            name='writing_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='batch_creation',
            name='date_time',
            field=models.TextField(default='2023-03-12 15:12:35.989871+05:30'),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='date_time',
            field=models.TextField(default='2023-03-12 15:12:35.989871+05:30'),
        ),
    ]
