# Generated by Django 4.0.3 on 2023-03-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0013_test_assigned_listening_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch_creation',
            name='assignment_array',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='batch_creation',
            name='date_time',
            field=models.TextField(default='2023-03-12 17:03:32.301647+05:30'),
        ),
        migrations.AlterField(
            model_name='user_login',
            name='date_time',
            field=models.TextField(default='2023-03-12 17:03:32.301647+05:30'),
        ),
    ]
